### ISSUE TITLE
Not Posting, logs show "not valid JSON error"

### ISSUE THREAD

**Issue by andrewc2** [Lucxjo/reddit-discord-bridge#9]
Not sure if something changed on the reddit api, or maybe this is a result of rate-limiting. I've turned off the container for now to see if restarting it in an hour clears it.

```
Version: 1.0.3
SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at parse (<anonymous>)
    at packageData (deno:ext/fetch/22_body.js:375:16)
    at Response.json (deno:ext/fetch/22_body.js:314:18)
    at async fetchSubredditData (file:///app/src/utils/fetchSubredditData.ts:30:36)
```

**Comment by andrewc2** [comment]
A friend confirmed he ran into the same issue with reddit, it is a form of rate limiting going on
